[package]
name = "bus-queue"
version = "0.1.0"
authors = ["Filip Dulic <filip.dulic@tradecore.com>"]
description = "Lock free bounded non blocking pub sub queue"
license = "Apache-2.0/MIT"
keywords = ["pubsub", "lock-free", "queue"]
repository = "https://github.com/filipdulic/bus-queue"
[dependencies]
arc-swap = "0.3.6"

[[example]]
name = "pubsub"
path = "examples/pubsub.rs"
